server:
  port: 8080
logging:
  config: classpath:logback.xml
spring:
  application:
    name: explorer
  aop:
    proxy-target-class: true
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://127.0.0.1:3306/explorer?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=round&characterEncoding=UTF-8&yearIsDateType=false&useSSL=true
    username: explorer
    password: 123456
    separator: ;
    name: explorer
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorermain
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 10
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
mybatis:
  executor-type: simple
  type-aliases-package: io.nebulas.explorer.domain
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
grpc:
  host: 52.76.103.107
  port: 8684
  enableKeepAlive: true
  keepAliveWithoutCalls: true
  keepAliveTimeout: 2
page:
  baseUrl: http://localhost:8080
  hostUrl: http://localhost:8080
sync:
  open: true
  subscribe : true
apiHost:
  coinmarketcap: https://api.coinmarketcap.com
  nebulas: http://52.76.103.107:8685
  gateio: https://data.gateio.io
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 2
environment: dev
pendingTxExpiredTime : 1

---
spring:
  profiles: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
environment: dev
pendingTxExpiredTime : 1

---
spring:
  profiles: test
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
  datasource:
    sql-script-encoding: UTF-8
    platform: mysql
    initialize: false
    schema: classpath:schema.sql
    url: jdbc:mysql://172.26.142.98:3306/explorer?autoCommit=true&autoReconnect=true&useUnicode=true&tinyInt1isBit=false&zeroDateTimeBehavior=round&characterEncoding=UTF-8&yearIsDateType=false&useSSL=false
    username: explorer
    password: kKIo0##D
    separator: ;
    name: explorer
    continue-on-error: false
    jmx-enabled: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: explorer
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000
      minimum-idle: 1
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
server:
  port: 32736
environment: test
page:
  baseUrl: http://39.98.232.55
  hostUrl: http://39.98.232.55
pendingTxExpiredTime : 1
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 2
---
spring:
  profiles: prod
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
environment: production
pendingTxExpiredTime : 48
